version: '3'

services:
#  watchtower:
#    image: containrrr/watchtower
#    restart: always
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#      - /etc/timezone:/etc/timezone:ro
#    environment:
#      - WATCHTOWER_CLEANUP=true
##      - WATCHTOWER_LABEL_ENABLE=true
#      - WATCHTOWER_INCLUDE_RESTARTING=true
##    labels:
##      - "com.centurylinklabs.watchtower.enable=true"


#  fhws:
#    image: ghcr.io/matthiasreining/fhws/fhws22-rooms
#    ports: 
#      - "80:8080"
##    labels:
##      - "com.centurylinklabs.watchtower.enable=true"


  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
  
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"


