version: '3'

services:

  fhws:
    image: ghcr.io/matthiasreining/fhws/fhws22-rooms
    depends_on:
      - "db"
    environment:
      DB_HOST: db
    ports:
      - "80:8080"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres@123#secret
    volumes:
      - "./storage/psql:/var/lib/postgresql/data"
      - "./:/scripts"
    
    # no public ports
    # ports:
    #   - "5432:5432"
  
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - "db"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - "./storage/pgadmin:/var/lib/pgadmin"
    ports:
      - "5050:80"

  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    environment:
      - WATCHTOWER_CLEANUP=true
    command: --interval 30
